sudo: false

language: python
cache: pip

matrix:
  include:
    - python: '3.5'
    - python: '3.6'
    - python: '3.6'
      env: PEP8=1

install:
  - pip install -r requirements.txt
  - |
    # Check if this is the PEP8 test instance and install pycodestyle
    if ! [ -z "$PEP8" ]; then
       pip install pycodestyle
    fi

before_script:
  - |
    # Install plugin and start ElasticSearch if not on the PEP8 test instance
    if [ -z "$PEP8" ]; then
      sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu
      sudo service elasticsearch start
      sleep 10 # While ElasticSearch starts up (as per Travis docs)
    fi

script:
  - |
    # Check if this is the PEP8 test instance and run pycodestyle
    if [ -z "$PEP8" ]; then
      python -m pytest -s tests
    else
      pycodestyle ./
    fi
