version: "3.8"
services:
  oracc-api:
    container_name: oracc-api
    restart: on-failure
    build:
      context: .
      dockerfile: ./compose/api/Dockerfile
    ports:
    - ${ORACC_PORT:-8000}:8000
    stdin_open: true
    tty: true
    environment:
    - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
    - elasticsearch

  elasticsearch:
    build:
      context: ./compose/elasticsearch
      dockerfile: Dockerfile
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    - http.cors.enabled=true
    - http.cors.allow-origin=/http:\/\/(elasticsearch|localhost):9200/
    volumes:
    - es_data:/usr/share/elasticsearch/data:rw

  oracc-ingest:
    container_name: oracc-ingest
    build:
      context: .
      dockerfile: ./compose/ingest/Dockerfile
    volumes:
    - ingest:/glossaries:ro
    depends_on:
    - elasticsearch

volumes:
  es_data:
  ingest:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ORACC_INGEST_DIRECTORY:-ingest/assets/dev/sample-glossaries}
