version: "3.8"
services:
  api:
    container_name: api
    restart: on-failure
    build:
      context: .
      dockerfile: ./compose/api/Dockerfile
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  elasticsearch:
    build:
      context: ./compose/elasticsearch
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node # this is for development only
      - xpack.security.enabled=false # this should be set to true in production
      - http.cors.enabled=true
      - http.cors.allow-origin=http://elasticsearch:9200
  ingest-service:
    build:
      context: .
      dockerfile: ./compose/ingest/Dockerfile
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch
