name: Run tests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: ["3.6", "3.9"]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}
                  cache: "pip"
            - name: Install Python dependencies if no cache found
              run: pip install -r requirements.txt
            - name: Configure sysctl limits # as suggested by action provider
              run: |
                  sudo swapoff -a
                  sudo sysctl -w vm.swappiness=1
                  sudo sysctl -w fs.file-max=262144
                  sudo sysctl -w vm.max_map_count=262144
            - name: Runs Elasticsearch
              uses: elastic/elastic-github-actions/elasticsearch@master
              with:
                  stack-version: 7.17.7 # version installed on server
                  plugins: analysis-icu
            - name: Run tests
              run: python -m pytest -s tests
